### ISSUE TITLE
[Question] The function of creating lighting for the object

### ISSUE THREAD

**Issue by MarkHollywood** [Zarig/DragonFF#1]
Will there be a function to create a lighting object for day and night time in the game?
I would like to see the import of models together with sources of lighting (**Light Point**)  according to the standard. @Zarig

**Comment by MarkHollywood** [comment]
Edit*
Day prelight:
![image](https://user-images.githubusercontent.com/29834790/53624368-42e35b00-3c2a-11e9-94eb-427ad5e08d9a.png)
Night prelight:
![image](https://user-images.githubusercontent.com/29834790/53624383-51ca0d80-3c2a-11e9-8e76-549efe7680dc.png)

**Comment by Zarig** [comment]
I do not quite understand your question. Do you mean the prelighting for object? In that case, it is already loaded as Vertex Colours. 

Lamps however, are not used in GTA to create lighting in objects, (unless some mod uses it, in which case I'd be happy to add a support), it is the Vertex Colour. In a standard map model, there are two vertex colours, night vertex colour and day vertex colour. They are used to add lighting to the object at night and day respectively. It is also possible for a sort of 'dynamic' lighting by enabling the export of normals (which is already, by default, enabled and cannot be disabled at this moment). Exporting the object with two vertex colours already disables the dynamic lighting though.

**Comment by MarkHollywood** [comment]
I said nonsense, forget it. Dynamic lighting is about what I said above, but I do not quite understand it is possible in DragonFF?

**Comment by Zarig** [comment]
Yes. As I said, dynamic lighting is enabled automatically if a map model has normals. The normals are exported automatically, for now, but there's no way to disable it.

To get dynamic lighting, you also need to remove the vertex colour layers.

**Comment by MarkHollywood** [comment]
Well, I will try to do it, I do not know if I can do it.

**Comment by Zarig** [comment]
Alright, good luck with it. Re-open this issue if you run into any problems.

**Comment by MarkHollywood** [comment]
I am very sorry, can not you write on the wiki page information about creating prlayt on the object.
I am a knowledgeable user of a blender, but in the new version I don’t understand much. It was not for me alone that it was interesting to read such information, future users of **DragonFF** will be glad of such information.

_I apologize for my stupidity._ @Zarig
