### ISSUE TITLE
Alpha Textures not work

### ISSUE THREAD

**Issue by dmsass** [Zarig/DragonFF#18]
Hi,

I realized that in the addon there is no support for alpha textures.

It would be nice to do this.

In game:
![Screen 1](https://imgur.com/fe2yT2d.png)

Textures in MagicTXD:
![Screen 2](https://imgur.com/Ekds2xE.png)

![Screen 3](https://imgur.com/zbrn1KJ.png)

**Comment by Zarig** [comment]
I'm fairly certain that there is support for Alpha textures in the scripts. Could you ensure that the textures are properly configured in both the DFF file and the TXD?

**Comment by dmsass** [comment]
I did everything right, but still the game does not work. Maybe the program needs to do something for this?

**Comment by Zarig** [comment]
Well, I'm not so sure about that. There doesn't seem to be anything transparent in the screenshot you sent.

**Comment by dmsass** [comment]
I do not understand why, but I impose a texture on the plane and on the reverse side the texture is not displayed. I know that game engines do not handle the reverse side of the polygon, BUT I added an alpha channel to this texture in the image editor.

**Comment by Zarig** [comment]
I would suggest you try the solidify modifier from the modifiers menu in Blender to overcome that problem, or enable no back-face culling in the object IDE flags (which I'm not sure how you'd do in MTA).

**Comment by dmsass** [comment]
Oh, thanks for the info on the modifier.
