### ISSUE TITLE
Work with 2D Effects

### ISSUE THREAD

**Issue by MarkHollywood** [Zarig/DragonFF#2]
When will the 2D Effects (**2dfx**) feature be implemented?

I know that there is a similar script for _Blender version 2.79_, even used it several times.

2dfx add-on:
![image](https://user-images.githubusercontent.com/29834790/53727027-7b3ca080-3e99-11e9-8051-4baf379084ca.png)

**Comment by Zarig** [comment]
Well, I'm working on it right now, and it should be completed fairly soon. It isn't a difficult thing to support, and will probably take a day or two to complete. I'm quite busy this week though, so I probably won't have time to add major features to the scripts, but I will look at it this weekend.

**Comment by MarkHollywood** [comment]
Just great, thanks!
