### ISSUE TITLE
Map Import Lacks a Button To Run

### ISSUE THREAD

**Issue by ThePortuguesePlayer** [Zarig/DragonFF#20]
I'm using the latest commit made at Jul 13, 2019.
I know the IPL importer is still being developed, but is it normal that I have no button to interact with in the UI to actually start the importing process? Is this the same for everyone?
![image](https://user-images.githubusercontent.com/47691365/61255783-f83e2780-a761-11e9-8714-a9469e141195.png)
Shouldn't there be a button in this panel to start importing the map?
Also, on 2.79, this panel, although present, is entirely empty.
There's nothing in the wiki mentioning the Map Import function of this addon yet.

**Comment by swift502** [comment]
Yyyeahhh. There should be a button on the bottom of the panel. 😄 I just installed it and it's the same for me.
I haven't done any 2.79 compatibility work, I only tested on 2.8 so I'm not surprised that it's not even there in 2.79, but the "Import" button should be there.

Maybe @Zarig did this intentionally, I don't know.

**Comment by Zarig** [comment]
Ah I realised that you didn't put the GUI or the operator classes in the class list to register, so they didn't get registered and hence didn't appear. I added the one for the panel, but must've forgotten to do that for the operator.

**Comment by swift502** [comment]
@ThePortuguesePlayer Btw if you really plan to import something, you'll need to extract all of the dff files from GTA 3's image archives yourself. (Using IMG tool for example)
That's where the "Dff folder" has to point to.

**Comment by ThePortuguesePlayer** [comment]
Yes, I already have them extracted and it is confirmed to be working now!
Seems like I also have to extract the textures out of all DFFs? All models are purple.
Thanks for solving this this quick. Blender is in real need for a truly good DFF addon.
I do my modeling on Blender, but I'm dependent on 3DS Max to export the models properly for my MTA server. The whole moving the files from one program to the other is a royal pain in the butt and it doesn't help I'm not a big fan of 3DS Max's confusing UI.
A weird issue also happens when importing a DFF that was exported using 3DS into Blender (using this or any other plugin), but I guess I should open a new issue for that.

**Comment by swift502** [comment]
Yeah there isn't any txd or img manipulation yet.

For now I've worked around it by extracting all of the textures as well ([here's](https://github.com/swift502/DragonFF/raw/BeamNG/assets.zip) a zip if you wanted), and in Blender you just go File > External Data > Find Missing Files and select the "png" folder. Blender links about 90% of the textures correctly. Some are wrong, which you'll just have to correct manually.

**Comment by ThePortuguesePlayer** [comment]
I see, thank you very much!
I had ran a batch export on my TXDs, but it failed to extract the Alpha channel out of some of the textures. Upon extracting those manually, everything works as it should.

**Comment by KingKalan** [comment]
im having an issue of nothing being imported when i import a map. blender appears to be loading and then there is nothing
