### ISSUE TITLE
[Help] 'Dynamic' lighting in object

### ISSUE THREAD

**Issue by MarkHollywood** [Zarig/DragonFF#3]
I am very sorry, can not you write on the wiki page information about creating 'dynamic' lighting on the object.
I am a knowledgeable user of a blender, but in the new version _2.8_ I don’t understand much. It was not for me alone that it was interesting to read such information, future users of **DragonFF** will be glad of such 
#1 
I apologize for my stupidity. @Zarig

**Comment by MarkHollywood** [comment]
Solved a problem
Day
![image](https://user-images.githubusercontent.com/29834790/53882873-ad890200-4041-11e9-86e2-8f1314654341.png)
Night
![image](https://user-images.githubusercontent.com/29834790/53882879-b4b01000-4041-11e9-993b-58eb97f06190.png)

**Comment by Zarig** [comment]
That is actually static lighting as it isn't affected by car headlights or other lights. I can make a wiki page for that if you'd like, but for dynamic lighting, it is enabled by default and is disabled if you add any vertex colours (which are used for the lighting you used in the post above).

**Comment by MarkHollywood** [comment]
Ohhh, that would be great. I did not know about such a function. Yes!

**Comment by MarkHollywood** [comment]
When are you planning to release a lesson on creating a dynamic insight? I can't finish creating my object for the game. @Zarig

**Comment by Zarig** [comment]
Well, all you have to do is export the model without any vertex colours (VCOLs). This method is used for player objects and vehicles. Objects with no vertex colours are affected by vehicle headlights and other directional lights. 

For map objects though, mostly the vertex colour method is used. In this method, there are two vertex colours. One is the day vertex colour, and the second is the night vertex colour. The day vertex colour is prevalent in the day, and night vertex colours at night, as the name suggests. This is what you had shown in your image.
By using Vertex Paint Mode in Blender, you can set up such night and day colour differences yourself.

I don't understand however, what is it exactly that you want to do with your object. Is it the dynamic lighting or the "baked" lighting?

**Comment by MarkHollywood** [comment]
Dynamic lighting

**Comment by MarkHollywood** [comment]
In the new version of the blender, I can not well use the function <Bake> (light baking), there are changes in contrast to 2.7x

**Comment by Zarig** [comment]
As I said, the dynamic lighting is automatically exported as long as you don't have baked lighting (i.e Vertex Colour Layers). You don't have to *do* anything to get it to work.

About the light baking, I think you have to switch to Cycles to do that. (or you can do it manually by using the Vertex Paint Mode)

**Comment by MarkHollywood** [comment]
Thanks for the information. Where can I write my 2dfx development proposal?

**Comment by Zarig** [comment]
You can reopen your previous issue about 2dfx and write it there, or else if you wish, you can post it here.

**Comment by MarkHollywood** [comment]
This can not be missed by innovation, I wanted to propose to take the functions of a ready-made script for 2dfx. If you want to look at them, I can attach a link to download it.

**Comment by MarkHollywood** [comment]
![image](https://user-images.githubusercontent.com/29834790/54494517-4999ef80-4905-11e9-90b0-c1e9980c730b.png)

**Comment by MarkHollywood** [comment]
![image](https://user-images.githubusercontent.com/29834790/54494563-dc3a8e80-4905-11e9-9dc5-381f4b3b8b64.png)

**Comment by MarkHollywood** [comment]
![image](https://user-images.githubusercontent.com/29834790/54494570-f2484f00-4905-11e9-80b8-08ab8f6a545a.png)

**Comment by Zarig** [comment]
That looks nice. Are these in a dummy object? (an empty?), because I was planning to use the actual Blender lights (or lamps) for the lights.

**Comment by MarkHollywood** [comment]
Yes, this dummy(empty). In my opinion, I worked back in 3ds Max and working with dummy is very convenient. I would not want to change it.

**Comment by Zarig** [comment]
The reason I wanted to go with lamps is that you'd be easily be able to distinguish them from other dummies that could be there in the scene. The lamps should be as easy to handle as the dummy. But I guess having too many lamps in one scene could mean a lot more computational power would be required to  render the scene. 

So I guess I'll go with dummies.  Any suggestions on what shape it could be? 

<img src="https://docs.blender.org/manual/en/latest/_images/modeling_empties_draw-types.png"/>

**Comment by MarkHollywood** [comment]
The dummy shape is a transparent square. For many users it will be convenient, do as you think best. But I would stop at dummy (entity)

**Comment by Zarig** [comment]
Well, you can shape the dummy however you like, and these are the shapes available (the ones in my last post). As the vehicle dummies and other dummies are also shaped as cubes, I thought it'd be better to have the 2dfx dummies shaped differently.

**Comment by MarkHollywood** [comment]
I think it is better to put a cube for 2dfx, since for most people it is usual for them.

**Comment by MarkHollywood** [comment]
I apologize, I thought for a long time, but nevertheless decided: you were right you need to put another figure in 2dfx. The cube will merge with dummy transport.
@Zarig
