### ISSUE TITLE
[Enhancement] Incorrect display of model type

### ISSUE THREAD

**Issue by MarkHollywood** [Zarig/DragonFF#4]
When exporting an object in the **.dff** format, I noticed a flaw: when executing a future model, the model type is not correctly set in the title bar of the future model.
In the screenshot **.blend**, and automatically should be **.dff**.
Please correct. :)

![image](https://user-images.githubusercontent.com/29834790/54999836-54d2d680-4ffb-11e9-89d2-8216366169fc.png)

**Comment by Zarig** [comment]
I believe this gives you more freedom to what you want the output file name to be. Also, as the Export DFF option could also be used to export COL files in the future (like the DFF Import can import col's).

Despite that though, I do think that such an enhancement would be good, and the custom extensions could be chosen through an extra option in the export settings :thinking:

**Comment by MarkHollywood** [comment]
Good!
