### ISSUE TITLE
[Bug] Model is not displayed in programs for viewing models.

### ISSUE THREAD

**Issue by MarkHollywood** [Zarig/DragonFF#5]
There is a need to prioritize on the model before exporting to the game.
 I used two programs for the test: 

- **DFF Viewer by Majestic (When loading the model, the program crashes)**
- **DFF Viewer by Dan (Not displayed)**
- **SA-MP kdff (v0.2.5) (Not displayed)**

I tried using the old add-on for _Blender 2.79_ (_by ponz_) and the model was very well displayed.
If possible, please correct.

![image](https://user-images.githubusercontent.com/29834790/55000823-8ba9ec00-4ffd-11e9-9a15-9020a1029d18.png)
![image](https://user-images.githubusercontent.com/29834790/55000891-a9775100-4ffd-11e9-8910-c5086e949b96.png)

**Comment by Zarig** [comment]
I'll take a look at that later today.

It appears from your the kdff screenshot that it did import the geometry (evident from the vertices and the faces count), but it didn't show up in the display. Perhaps the camera is placed away from or directly inside the model?

**Comment by MarkHollywood** [comment]
No, the camera is standard on the model.

**Comment by Zarig** [comment]
Either way, it isn't a bug of the scripts, but rather the programs that you use to view them. I however, don't see the need for a DFF Viewer if you use the Blender scripts anyway.

**Comment by MarkHollywood** [comment]
Ok
