### ISSUE TITLE
[Error] The problem with the compatibility and drawing of the model in 3D view programs.

### ISSUE THREAD

**Issue by MarkHollywood** [Zarig/DragonFF#9]
# The problem with the compatibility and drawing of the model in 3D view programs.

Not so long ago, the Russian community faced the problem of importing the **.dff** model (Made in Blender 2.8 -> **DragonFF Script**) to Autodesk 3ds Max 2017, used by **Kam 's Script**.

![Error Kam's Script](https://imgur.com/OPyE2Tn.png)

And there is also an error in displaying the model in the 3D display programs. For example, in the **Kdff** program for creating and viewing **.dff** models, there are no errors, and the model is not displayed. **From this it follows that people cannot create a collision for an object.**

![Kdff error](https://imgur.com/rKGCNay.png)

It seems to me that these errors are due to your script, because In the old script of 2011(gtatools), everything works fine.

**Please correct this misunderstanding, as our large community does not have the ability to edit models from Blender 3D, and create a collision. This hampers the development of this add-on for the Russian-speaking mobile community in GTA modding.**
Waiting for an answer. :)

**Comment by Zarig** [comment]
Not sure why the KAMS Error occurred though, need more information on that.

About the DFF Viewer errors, it is because the tool doesn't export Bin Mesh PLG data yet, which isn't required for the game, but I guess the tools need it for importing the model. I'm working on including that in the next version of the scripts along with other enhancements including improved Normals export, and duplicate detection. 

Thanks for the report.

**Comment by MarkHollywood** [comment]
I can’t temporarily say the details of this error, I know that when I import a model in **.dff** format into _3ds Max_, I get an error. I assume that you need to consider yourself Kam's Script.

I hope you will find a solution, because our community is worried about the compatibility of **.dff** in 3D editors.
@Zarig

**Comment by Zarig** [comment]
@MarkHollywood Can you check if the model displays correctly in your DFF Viewers in the latest version?

**Comment by MarkHollywood** [comment]
@Zarig 
Error in Export Model
![Error](https://imgur.com/hVrc1Df.png)

**Comment by Zarig** [comment]
Thank you, @MarkHollywood. I've fixed this in the latest commit.

**Comment by MarkHollywood** [comment]
You are already close, but some irregularities and breaks in the model. On the past screen was almost flat surface. On the screen is damaged. @Zarig 
![xD](https://imgur.com/3tYEEWw.png)

**Comment by Zarig** [comment]
Well, I'm not sure what's wrong there, the model imports fine in Blender even with the "Import Material Split" option checked. :man_shrugging:

**Comment by MarkHollywood** [comment]
You misunderstood me.
I made a model in a blender and exported it through your scripts, but in the program for displaying **.dff** models, it is distorted, some points are generally far away.
Blender:
![bl](https://imgur.com/M9FdjQy.png)

KdffGUI:
![kd](https://imgur.com/yGDmffe.png)

The screenshots show that the script does not accurately export the model vertices. I hope you fix it. Thanks for your support. @Zarig

**Comment by Zarig** [comment]
Well it surely does export them properly as they can be imported back just fine, and they look alright ingame too. I'm not sure what causes that in KDFF, and it is indeed a KDFF bug and not a bug with my scripts.

**Comment by MarkHollywood** [comment]
True, I bring my apologies. All the same problem in the program itself.
![s](https://imgur.com/5johkkq.png)

**Comment by MarkHollywood** [comment]
@Zarig
